---
title: "cap1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r echo=FALSE, include= FALSE}
# Loading libriry
library(tidyverse)
library(caret)
library(dplyr)

```


```{r echo=FALSE, include=FALSE}
# Import Data
Bitcoin <- read_csv("data/BitcoinHeistData.csv")

```

```{r}
# Check the number of rows and columns the data frame has
dim(Bitcoin)
```


```{r}
# Clean the data
# check there is a missing value
sum(is.na(Bitcoin))
```

```{r}
# Visualization missing data
library(naniar)
vis_miss(sample_n(Bitcoin, 90000))
```

```{r}
# Analyzing categorical variables
library(funModeling) 
#library(Hmisc)
freq(Bitcoin)
```


```{r}
# Analyzing numerical variables
plot_num(Bitcoin)
```


```{r}
# Analyzing numerical and categorical at the same time
 describe(Bitcoin)
```


```{r}
# Data Visualization 
library(corrplot)
M<-cor(Bitcoin[,c(-1,-10)])
corrplot(M, method="number", type="upper", order="hclust", )
```


```{r}

library(hrbrthemes)
library(viridis)
library(babynames)

ggplot(Bitcoin, aes(x=year, y=weight, group=label, fill=label)) +
    geom_line() +
    theme(legend.position="none") +
    ggtitle("Longitudinal payment trend per family") +
    theme_ipsum() +
    theme(
      legend.position="none",
      panel.spacing = unit(0, "lines"),
      strip.text.x = element_text(size = 8),
      plot.title = element_text(size=13)
    ) +
    facet_wrap(~label, scale="free_y")
```


```{r echo=FALSE, include=FALSE}

# split data to train and test data

library(rsample)
set.seed(123)
split <- initial_split(Bitcoin, prop = .7)
bitcoin_train <- training(split)
bitcoin_test <- testing(split)
```


_________________________ SVM __________________________ 


```{r}
# apply Support Vector Machines   sample_n(bitcoin_train, 10000

library(e1071)
classifier <- svm(
                  formula = factor(label) ~ .,
                  data = sample_n(bitcoin_train, 10000),  
                  method = 'C-classification',
                  kernel= 'radial')
summary(classifier)
```

```{r}
predsvm <- fitted(classifier)

# # Model Evauation  Matrix 
cmsvm <- confusionMatrix(predsvm, bitcoin_test$label)
cmsvm

```

 ________________________ NB__________________________ 
 

```{r}
# Naive Bayes 
library(e1071) 
library(caTools) 
library(caret) 

# Fitting Naive Bayes Model  
NB <- naiveBayes(factor(label) ~ ., data = sample_n(bitcoin_train, 500000)) 

  
```


```{r} 
# Predicting on test data' 
bitcoin_test$label <- as.factor(bitcoin_test$label)
bitcoin_test$label
predNB <- predict(NB, bitcoin_test$label) 

# # Model Evauation  Matrix 
cmnb <- confusionMatrix(predNB, bitcoin_test$label)
cmnb
```

______________________ #DBScan ______________________- ( not yet )

```{r}
library("fpc")
# Compute DBSCAN using fpc package
set.seed(123)
DBS <- as.matrix(bitcoin_train[,2:9])
db <- fpc::dbscan(DBS, eps = 0.15, MinPts = 5)
# Plot DBSCAN results
plot(db, DBS, main = "DBSCAN", frame = FALSE)
```




```{r}
#DBScan 
library(fpc) 
library(dbscan)
DBS <- as.matrix(bitcoin_train[,2:9])
  #bitcoin_train[, c(-1,-10)]

# fitting DBScan clustering
Dbscan_cl <- dbscan(DBS, eps = 0.45, MinPts = 5)
Dbscan_cl 
```


```{r}
# Checking cluster 
Dbscan_cl$cluster 
```

```{r}
table(Dbscan_cl$cluster, bitcoin_train$label) 

```

```{r}

# Plotting Cluster 
plot(Dbscan_cl, DBS, main = "DBScan") 

```


----------------- random Forest--------------------

```{r}


# Load the library 
library(randomForest) 

# Create random forest 
# For classification 
rf.cl <- randomForest(factor(label) ~ .,  
                        data = sample_n(bitcoin_train, 10000),  
                        importance = TRUE, 
                        proximity = TRUE) 
rf.cl
```


```{r}
plot(rf.cl)
```


```{r} 
# Predicting the Test set results 
predrf = predict(rf.cl, newdata = bitcoin_test[-10]) 
  
```

```{r}

# # Model Evauation  Matrix 
cmrf <- confusionMatrix(predrf, bitcoin_test$label)
cmrf
```


